### ISSUE TITLE
Pod이 available하지 않을 때 log exception handling이 잘 되지 않는 현상

### ISSUE THREAD

**Issue by JunhoeKim** [onetop21/MLAppDeploy#121]
reproduce하는 방법: gpu가 없는 환경에 gpu를 포함시킨 mlad job을 배포하고 log를 가져오려고 하면 kubernetes 단에서 400에러가 나는데 이걸 mlad-apiserver에서 처리하지 못해서 이를 해결해야 합니다.

**Comment by kkkdeon** [comment]
재현 불가로 보류
