### ISSUE TITLE
부하가 큰 경우에 nginx-ingress에서 502 오류 발생

### ISSUE THREAD

**Issue by JunhoeKim** [onetop21/MLAppDeploy#130]
10.42.0.1 - - [09/Nov/2021:04:32:15 +0000] "POST /ingress/yoonhee/yoonhee-mpp-a5a3cbc813-cluster/fmr/mpp_fmr HTTP/1.1" 502 150 "-" "Python/3.7 aiohttp/3.8.0" 6390427 0.197 [yoonhee-mpp-a5a3cbc813-cluster-fmr-8443] [] 10.42.13.213:8443 0 0.112 502 a210ec2144c115d3eb56d5721c62a731
2021/11/09 04:32:15 [error] 3702#3702: *306824 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 10.42.0.1, server: _, request: "POST /ingress/yoonhee/yoonhee-mpp-a5a3cbc813-cluster/fmr/mpp_fmr HTTP/1.1", upstream: "http://10.42.13.213:8443/mpp_fmr", host: "ncml-dev.cloud.ncsoft.com"

**Comment by onetop21** [comment]
Standalone으로 테스트 해보고 문제가 있으면
ingress-nginx 대신 traefik이나 ambassador로 교체 후 테스트 진행
