### ISSUE TITLE
project workdir 변경 이슈

### ISSUE THREAD

**Issue by JunhoeKim** [onetop21/MLAppDeploy#19]
mlad project up을 한 후에 여러 이유로 work directory의 구조가 변경되면 해당 project를 다시 down 할 수 없는 상황이 발생합니다.

**Comment by onetop21** [comment]
mlad ls 로 project key를 가져오게 해서
mlad down -k project_key 이렇게하면 되지 않을까? 라고 생각합니다. ;)
