### ISSUE TITLE
Context 나머지 명령어 처리 기능을 구현

### ISSUE THREAD

**Issue by JunhoeKim** [onetop21/MLAppDeploy#25]
Related to #20 

Context 객체를 정의하면서 **add**와 **use** 기능을 구현했습니다.
마찬가지 방법으로 delete, ls, get, set 기능을 추가하려고 합니다.

**Comment by onetop21** [comment]
next
prev
switch

**Comment by JunhoeKim** [comment]
각 context를 별도의 파일로 사용하고 있는 로직을 하나의 파일로 수정하고 next, prev 기능을 추가하려고 합니다.
