### ISSUE TITLE
MLAD Labeling 기능 관련 이슈

### ISSUE THREAD

**Issue by TaehwanKwon** [onetop21/MLAppDeploy#7]
actor_cloud:
     env:
         MODE: learning
     command:
         python actor.py connection=mlad-lb controller=dev-taehwan learning=mlad1
     deploy:
         constraints:
             hostname: th01, th02, th03
         replicas: 8

이런 식으로 클라우드 인스턴스 여러 개를 동시에 같은 조건으로 돌리고 싶습니다.

이와 관련하여 LABEL 기능 활용이 필요할 것 같은데 어떻게 하는게 좋을까요?

**Comment by onetop21** [comment]
Node에 Label을 넣는 방법으로 해당 이슈는 처리가 가능하며
Label 추가 시 이슈는 해결했습니다.
사용법은 README.md에 남겨놓겠습니다.
