### ISSUE TITLE
ingress 사용시에 접근해야하는 base url 정보를 띄워주기

### ISSUE THREAD

**Issue by JunhoeKim** [onetop21/MLAppDeploy#73]
Deployment 기능을 사용하는 입장에서 어떤 url을 써야하는지 알기가 어려워서 이에 대한 안내 문구가 필요합니다.

**Comment by kkkdeon** [comment]
- deploy기능에는 추가 예정
- project는 ingress를 열어줄지 말지 결정되면 결정
