### ISSUE TITLE
app image에서 retag 여부 판단

### ISSUE THREAD

**Issue by JunhoeKim** [onetop21/MLAppDeploy#91]
app의 image로 지정될 때 과거 버전의 이미지를 쓰기 위해서 local image를 사용했을 때 registry가 반영이 안되어있으면 retag와 push를 다시 해줘야한다.

예를 들어, 이미지를 한 번 빌드하면 local에 `mlad/example-321bf321af:0.0.1` 과 같이 이미지가 생기고 최초 1회 up을 할 때 `harbor.sailio.ncsoft.com/mlad/example-321bf321af:0.0.1`과 같이 retag를 하는데 app의 image property에 retag 전 tag인  `mlad/example-321bf321af:0.0.1` 를 부여하면 문제가 생긴다 (remote에 해당 이미지가 없으므로). 그러면 retag를 자동으로 해줘야할까 아니면 docker hub 공식 이미지랑 구별할 방법이 없으므로 사용자가 조심해서 쓰도록해야할까?

**Comment by JunhoeKim** [comment]
build 단계에서 project의 kind가 Deployment, Train이면 remote 기준으로 tag 후 push까지
kind가 component면 local 이름으로 tag 후 push 없이 build만 합니다.

**Comment by onetop21** [comment]
class images:
  def build():
     if root.kind in ['Train', 'Deployment']:
        name = {repo}/{name}:latest
     else:
        name = {name}:latest
    build ....
     if root.kind in ['Project', 'Deployment']: push()

def install(nobuild):
   if not nobuild: ... .build()
  docker run -d ...

def up(nobuild):
   if not nobuild: ... .build()
  kubectl apply -f ...
